/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as LegalRouteRouteImport } from './routes/_legal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LegalTermsRouteImport } from './routes/_legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/_legal/privacy'

const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_legal': typeof LegalRouteRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/_legal/privacy': typeof LegalPrivacyRoute
  '/_legal/terms': typeof LegalTermsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rss.xml'
    | '/privacy'
    | '/terms'
    | '/api/search'
    | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rss.xml' | '/privacy' | '/terms' | '/api/search' | '/docs/$'
  id:
    | '__root__'
    | '/'
    | '/_legal'
    | '/rss.xml'
    | '/_legal/privacy'
    | '/_legal/terms'
    | '/api/search'
    | '/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal/terms': {
      id: '/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/_legal/privacy': {
      id: '/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
  }
}

interface LegalRouteRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
